[development]
HOST="127.0.0.1"
PORT="5432"
DBNAME="my_dev_db"
DBUSER="me"
DBPASSWORD="changeme"

[production]
HOST="127.0.0.1"
PORT="5432"
DBNAME="my_production_db"
DBUSER="admin"
DBPASSWORD="adminpass"
