[development]
SQLITE_DBNAME="my_dev_sqlite.db"
HOST="127.0.0.1"
PORT="5432"
DBNAME="my_dev_db"
DBUSER="me"
DBPASSWORD="changeme"

[production]
SQLITE_DBNAME="my_prod_sqlite.db"
HOST="127.0.0.1"
PORT="5432"
DBNAME="my_production_db"
DBUSER="admin"
DBPASSWORD="adminpass"
