[default]
# veja em https://dynaconf.readthedocs.io/en/docs_223/guides/environment_variables.html
CURRENT_ENV = "@jinja {{this.current_env | lower}}" # development or production
HOME_DIR = "@jinja {{env.HOME}}"
DIR_INPUT="Entrada"
DIR_OUTPUT="Saida"
LOG_MONITOR = "logs/myprogram.log"

[production]
DIR_SAIDA="@jinja {{this.DIR_OUTPUT}}/production"

[development]
DIR_SAIDA="@jinja {{this.DIR_OUTPUT}}/development"
